### PR TITLE
PMK-3950 Updated from go 1.17 to go 1.19

### PR DESCRIPTION
**Pull request by jayanth-tjvrr**
## ISSUE(S):
[PMK-3950](https://platform9.atlassian.net/browse/PMK-3950)

Updated go from v.17 to 1.19 to resolve some of the vulnerabilities

[PMK-3950]: https://platform9.atlassian.net/browse/PMK-3950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by manasabsv26** [comment]
Trivy scan report:
```
docker.io/platform9/whereabouts:v0.6-pmk- (alpine 3.18.2)

Total: 0 (HIGH: 0, CRITICAL: 0)
```

**Review by cruizen — APPROVED** [review]
LGTM. Thanks. (This has been done in the upstream repo too. So check there if there's anything else that we missed.)

**Comment by cruizen** [comment]
The CI action test is failing since it probably requires a newer version of the go-revive action? https://github.com/platform9/whereabouts/actions/runs/5516902942/jobs/10058824617?pr=17 I also saw some `go vet` failures in a branch - that might come up next.

**Comment by cruizen** [comment]
> The CI action test is failing since it probably requires a newer version of the go-revive action? 

Thanks @manasabsv26 for taking care of this. 

The test action is now failing with 

> hack/../pkg is out of date. Please run hack/update-codegen.sh
> Error: Process completed with exit code 1.
> 

From the job : https://github.com/platform9/whereabouts/actions/runs/5531045667/jobs/10091216021

**Comment by manasabsv26** [comment]
Tested on 1.25 cluster, whereabouts pod came up fine
Luigi pod events
```
Events:
  Type    Reason          Age   From               Message
  ----    ------          ----  ----               -------
  Normal  Scheduled       47s   default-scheduler  Successfully assigned luigi-system/luigi-controller-manager-66cc4588cb-qb22k to 10.128.147.42
  Normal  AddedInterface  47s   multus             Add eth0 [10.20.20.152/32] from k8s-pod-network
  Normal  Pulled          46s   kubelet            Container image "gcr.io/kubebuilder/kube-rbac-proxy:v0.11.0" already present on machine
  Normal  Created         46s   kubelet            Created container kube-rbac-proxy
  Normal  Started         46s   kubelet            Started container kube-rbac-proxy
  Normal  Pulling         46s   kubelet            Pulling image "platform9/luigi-plugins:private-v0.5.0-manasa-whereabouts-pmk-2752253"
  Normal  Pulled          44s   kubelet            Successfully pulled image "platform9/luigi-plugins:private-v0.5.0-manasa-whereabouts-pmk-2752253" in 2.305638041s
  Normal  Created         44s   kubelet            Created container manager
  Normal  Started         43s   kubelet            Started container manager
```

whereabouts pod events:
```

Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  30s   default-scheduler  Successfully assigned luigi-system/whereabouts-7vrww to 10.128.147.42
  Normal  Pulling    30s   kubelet            Pulling image "docker.io/platform9/whereabouts:v0.6-pmk-2750811"
  Normal  Pulled     25s   kubelet            Successfully pulled image "docker.io/platform9/whereabouts:v0.6-pmk-2750811" in 4.836948725s
  Normal  Created    25s   kubelet            Created container whereabouts
  Normal  Started    25s   kubelet            Started container whereabouts
```

Pods:
```
kubernetes-dashboard     kubernetes-dashboard-579ddcbf4d-q9lrk        1/1     Running            0               18h
luigi-system             hostplumber-controller-manager-zxwd5         2/2     Running            0               18h
luigi-system             kube-multus-ds-amd64-7fdxx                   1/1     Running            0               35s
luigi-system             luigi-controller-manager-66cc4588cb-qb22k    2/2     Running            0               66s
luigi-system             whereabouts-7vrww                            1/1     Running            0               14s
node-feature-discovery   nfd-master-bd9546c66-67t46                   1/1     Running            0               18h
```

/cc @jayanth-tjvrr  @srinivaschavan

**Comment by cruizen** [comment]
@jayanth-tjvrr / @manasabsv26 you can merge this since the changes have been tested by Jayanth and then Manasa - let's track the test failure from CI separately https://github.com/platform9/whereabouts/actions/runs/5596776688/jobs/10234248797?pr=17

**Review by manasabsv26 — APPROVED** [review]

**Pull request merged**
