### PR TITLE
PMK-3950 Resolving vulnerabilities for whereabouts

### PR DESCRIPTION
**Pull request by manasabsv26**
## ISSUE: 
[PMK-3950](https://platform9.atlassian.net/browse/PMK-3950)

## SUMMARY:

Upgraded go packages to resolve vulnerabilities, built the image locally, running a trivy scan shows that it no longer has any HIGH/CRITICAL vulns.

```
docker.io/platform9/whereabouts:latest (alpine 3.18.2)

Total: 0 (HIGH: 0, CRITICAL: 0)
```

[PMK-3950]: https://platform9.atlassian.net/browse/PMK-3950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by cruizen** [comment]
Hi @manasabsv26 , there's a vendoring error in https://github.com/platform9/whereabouts/actions/runs/5419934988/jobs/9853533268?pr=15#step:5:5 
Can you run `go mod vendor` again with go 1.17 (used in go.mod)? 

BTW, @jayanth-tjvrr is using go 1.19 for his other fix (PR open) - check with him.

**Comment by jayanth-tjvrr** [comment]
@manasabsv26 In my [PR](https://github.com/platform9/whereabouts/pull/15), I have updated the golang to 1.19 and after go mod tidy I don't see any vulnerabilities there. I published a 0.4.12 image with my fixes and just backpoted those fixes here. I guess we can close this PR right. 
image
cc: @cruizen

**Comment by manasabsv26** [comment]
Ok great @jayanth-tjvrr , In that case, can close this PR.
Do we have to port the fixes made to `0.4.12` to master branch though? I see we have go version 1.17 in master branch and 1.19 in `0.4.12` branch

**Comment by manasabsv26** [comment]
Closing this PR, these changes have been made upstream, can sync fork

**Pull request closed without merging**
